### ISSUE TITLE
Removing path requirements

### ISSUE THREAD

**Issue by nicolaromano** [cmcdougall5/scRNAseq_pipeline#6]
To make the code more portable, it is useful not to set a hard-coded directory using `setwd`.
Instead, use package `here` to automatically infer paths.

Since your files are in a project, `here` will automatically use the path of the .RProj file as the location.

`setwd(here())`

You can then put your data files in subdirectories of your project and reference them using a relative path

`Read10X("Cheung") # This will be relative to your project path`

**Comment by cmcdougall5** [comment]
Hi Nico,

Many thanks for this suggestion and making me aware of the `here` package. I have implemented this change now.

best wishes,

Craig
